spring.application.name=HealthCare-Backend

# ✅ MySQL Connection (Aiven Cloud)
spring.datasource.url=jdbc:mysql://healthcare-ankitdoi82-3a73.d.aivencloud.com:10183/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ✅ JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ✅ Initialization
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ✅ JWT Secret Key
app.jwt.secret=aVeryLongAndSecureSecretKeyForYourApplicationThatShouldBeKeptSafe

# ✅ Admin Credentials
app.admin.email=admin@healthcare.com
app.admin.password=$2a$12$OxDAs7w9iv6Vw81RDR/WvuR/ZzD.3J32BZs5HvVhT5UCzqSLN4RGi

# ✅ JSON case-insensitive enums
spring.jackson.mapper.accept-case-insensitive-enums=true
